name: AI Code Review with Hugging Face

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write  # PR에 대한 읽기/쓰기를 명시적으로 설정

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch PR Files
        id: pr_files
        run: |
          # GitHub CLI 로그인 시도
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          
          # PR 변경 파일 목록을 가져오기
          echo "Fetching files for PR #${{ github.event.pull_request.number }}..."
          FILES=$(gh pr view 1 --json files --jq ".files[].filename")
          
          # 파일 목록이 비어있는지 확인
          if [ -z "$FILES" ]; then
            echo "No files changed in this PR."
            exit 1  # 파일이 없다면 CI를 종료
          fi

          echo "FILES=$FILES" >> $GITHUB_ENV
          echo "Fetched files: $FILES"  # 추가된 디버깅 정보
