name: Reviewdog Code Review

on:
  pull_request:

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # PR에 댓글을 달려면 필요

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # PR의 diff를 정확히 가져오기 위해 필요

      - name: Install Reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Run Custom Review Script
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Reviewing $file"
            # 원하는 코드 리뷰 로직 추가 (예: 특정 코드 패턴 검출)
            grep -n "TODO" "$file" | reviewdog -efm="%f:%l:%m" -name="TODO Review" -reporter=github-pr-review -filter-mode=diff_context || true
          done
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
