name: Gemini Code Review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write 

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq curl

      - name: Generate Code Review with Gemini API
        run: |
          DIFF=$(git diff origin/main...HEAD)
          REVIEW=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent?key=${{ secrets.GEMINI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{
              'contents': [{
                'parts': [
                  {'text': '
                    You're a sophisticated software engineer.
                    Please review the code changes in the following Pull Request and point out potential problems or areas for improvement only if they are significant.
                    Important rules about the diff format:
                    - Lines that begin with "-" are lines that have been **removed** in this Pull Request.
                    - Lines that begin with "+" are lines that have been **added** in this Pull Request.
                    - Lines that begin with a space " " are context lines, which have not changed.

                    Review guidelines:
                    - Ignore changes that only involve whitespace, indentation, or formatting that do not affect the code’s behavior.
                    - Do not add any review comments for trivial or non-impactful changes (e.g., variable name changes that do not affect logic).
                    - For suggestions, assign a priority (e.g., PRIORITY:HIGH, PRIORITY:MEDIUM, PRIORITY:LOW).
                    - Use type=POSITIVE only for changes that bring a clear, significant improvement to readability, performance, or maintainability. If a change is merely "not a problem," do not comment on it.
                    - Your review must be written in ${language}.

                    Diffs:
                    $DIFF}
                  ' 
                ]
              }]
            }" | jq -r '.candidates[0].content.parts[0].text')

          echo "Review result:"
          echo "$REVIEW"

          # PR에 코멘트 추가
          echo "$REVIEW" > review_comment.txt

      - name: Post Review Comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          message-path: review_comment.txt
          repo-token: ${{ secrets.GITHUB_TOKEN }}
