name: AI Code Review with Hugging Face

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install necessary dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git cmake make g++ unzip wget curl

      # 3. Setup Hugging Face API Token (stored in GitHub secrets)
      - name: Setup Hugging Face Token
        run: |
          echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV

      # 4. Clone llama.cpp repository
      - name: Clone llama.cpp repository
        run: git clone https://github.com/ggerganov/llama.cpp.git

      # 5. Build llama.cpp using CMake
      - name: Build llama.cpp using CMake
        run: |
          cd llama.cpp
          mkdir build && cd build
          cmake ..
          cmake --build . --parallel

      # 6. Download model from Hugging Face using the API token
      - name: Download model from Hugging Face
        run: |
          mkdir -p models
          curl -L -H "Authorization: Bearer $HUGGINGFACE_TOKEN" \
            -o models/tinyllama.gguf \
            https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-GGUF/resolve/main/tinyllama.gguf

      # 7. Fetch the code diff from the pull request
      - name: Fetch PR Diff
        id: pr_diff
        run: |
          DIFF=$(gh pr view ${{ github.event.pull_request.number }} --json diff --jq ".diff")
          echo "DIFF=$DIFF" >> $GITHUB_ENV

      # 8. Run AI Code Review
      - name: Run AI Code Review
        run: |
          cd llama.cpp/build
          ./bin/main -m ../../models/tinyllama.gguf -p "Review this code diff:\n$DIFF" > ../../review.txt

      # 9. Post AI review as a comment to the pull request
      - name: Post AI Review as Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Action에서 기본 제공하는 토큰
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub CLI에 사용할 토큰
        run: |
          COMMENT=$(cat review.txt)
          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"
