name: AI Code Review with Hugging Face

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write  # PR에 대한 읽기/쓰기를 명시적으로 설정

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install necessary dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git cmake make g++ unzip wget curl

      # 3. Setup Hugging Face API Token (stored in GitHub secrets)
      - name: Setup Hugging Face Token
        run: |
          echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV

      # 4. Clone llama.cpp repository
      - name: Clone llama.cpp repository
        run: git clone https://github.com/ggerganov/llama.cpp.git

      # 5. Build llama.cpp using CMake
      - name: Build llama.cpp using CMake
        run: |
          cd llama.cpp
          mkdir build && cd build
          cmake ..
          cmake --build . --parallel
          # 빌드 후 ./bin/main 파일이 있는지 확인
          ls -l ./bin  # 이 부분 추가: main 파일 확인

      # 6. Download model from Hugging Face using the API token
      - name: Download model from Hugging Face
        run: |
          mkdir -p models
          curl -L -H "Authorization: Bearer $HUGGINGFACE_TOKEN" \
            -o models/tinyllama.gguf \
            https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-GGUF/resolve/main/tinyllama.gguf

      # 7. Fetch the code diff from the pull request using files instead of diff
      - name: Fetch PR Files
        id: pr_files
        run: |
          # GitHub CLI 로그인 시도
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          
          # PR 변경 파일 목록을 가져오기
          echo "Fetching files for PR #${{ github.event.pull_request.number }}..."
          FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq ".files[].filename")
          
          # 파일 목록이 비어있는지 확인
          if [ -z "$FILES" ]; then
            echo "No files changed in this PR."
            exit 1  # 파일이 없다면 CI를 종료
          fi

          echo "FILES=$FILES" >> $GITHUB_ENV
          echo "Fetched files: $FILES"  # 추가된 디버깅 정보

      # 8. Run AI Code Review
      - name: Run AI Code Review
        run: |
          cd llama.cpp/build
          DIFF_TEXT="Reviewing the following files: $FILES"
          ./bin/main -m ../../models/tinyllama.gguf -p "$DIFF_TEXT" > ../../review.txt

      # 9. Post AI review as a comment to the pull request
      - name: Post AI Review as Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Action에서 기본 제공하는 토큰
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub CLI에 사용할 토큰
        run: |
          COMMENT=$(cat review.txt)
          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"
